# Generated by Django 3.2 on 2024-02-11 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_govt_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('taluk', models.CharField(max_length=50)),
                ('dob', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('housename', models.CharField(max_length=50)),
                ('housenumber', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('DOB', 'Date of Birth certificate'), ('DTH', 'Death certificate'), ('MC', 'Marriage certificate')], default='DOB', max_length=5)),
                ('certificate_filetype', models.CharField(choices=[('PNG', 'PNG'), ('PDF', 'PDF'), ('JPEG', 'JPEG')], max_length=5)),
                ('date_of_issue', models.DateField()),
                ('issued_by', models.CharField(max_length=50)),
                ('issued_to', models.CharField(max_length=50)),
                ('issued_to_address', models.CharField(max_length=50)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentryapp.citizen')),
            ],
        ),
    ]
